### ISSUE TITLE
http-proxy dep is outdated

### ISSUE THREAD

**Issue by aendrew** [SimonDegraeve/koa-browser-sync#4]
When I try to run it via `babel-node`, I get:

```
> babel-node --presets=es2015-node6,stage-2 "server/index.js"

util.js:947
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:947:11)
    at Object.<anonymous> (/Users/andrew.rininsland/Projects/starter-kit/node_modules/koa-browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/andrew.rininsland/Projects/starter-kit/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

Edit: After some investigation, the issue is not with `koa-browser-sync` but its dependency on `node-http-proxy`; see hipache/hipache#235.

Replacing the dependency with the latest version enables `koa-browser-sync` to work (even via `koa-convert` in Koa2!).

**Comment by SimonDegraeve** [comment]
The module is now updated to run with the latest versions of Koa and BrowserSync.
